version: 2.1

executors:
  miniconda3:
    docker:
    - image: continuumio/miniconda3:latest
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD
    working_directory: ~/project
    shell: /bin/bash --login -eo pipefail

commands:
  install-deps:
    description: Install dependencies via conda.
    parameters:
      version:
        description: Python version.
        type: string
    steps:
    - run:
        name: Install dependencies
        command: |
          conda create -y -n relentless-test python=<< parameters.version >>
          conda activate relentless-test
          conda install -y -c defaults --file requirements.txt
          conda env update -y -f tests/environment.yml

  test:
    description: Run tests
    steps:
    - run:
        name: Run tests
        command: |
          conda activate relentless-test
          python3 -m unittest discover -v

jobs:
  test:
    parameters:
      version:
        type: string
    executor:
      name: miniconda3
    resource_class: small
    steps:
    - checkout
    - install-deps:
        version: << parameters.version >>
    - test

workflows:
  test:
    jobs:
    - test:
        context: docker-hub-creds
        matrix:
          parameters:
            version: ["3.6","3.7","3.8"]
