version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  test:
    parameters:
      version:
        type: string
    executor:
      name: python/default
      tag: << parameters.version >>
    resource_class: small
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/test

workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              version: ["3.6","3.7","3.8"]
